# Generated by Django 4.0.3 on 2022-04-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_firststepmembers_student_middlename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firststepmembers',
            name='user',
        ),
        migrations.AddField(
            model_name='firststepmembers',
            name='first_name',
            field=models.CharField(default=0, max_length=20, verbose_name='Ismi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firststepmembers',
            name='last_name',
            field=models.CharField(default=0, max_length=20, verbose_name='Familiyasi'),
            preserve_default=False,
        ),
    ]
