# Generated by Django 4.0.3 on 2022-04-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_secondstepmembers_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firststepmembers',
            name='student_id',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='firststepmembers',
            name='student_class',
            field=models.CharField(choices=[('3 - sinf', '3 - sinf'), ('4 - sinf', '4 - sinf'), ('5 - sinf', '5 - sinf'), ('6 - sinf', '6 - sinf'), ('7 - sinf', '7 - sinf')], max_length=20, verbose_name='Sinfi'),
        ),
    ]
